-- This is the way how write comment in sql
/*
 This is how you write multi line comment
 */
SELECT * FROM REGIONS ;
SELECT * FROM COUNTRIES ;
select * from EMPLOYEES ,JOB_HISTORY,JOBS,LOCATIONS,REGIONS;
SELECT *FROM EMPLOYEES ;
SELECT FIRST_NAME , LAST_NAME FROM EMPLOYEES ;
select DISTINCT FIRST_NAME
FROM EMPLOYEES ;

SELECT DISTINCT LAST_NAME
FROM  EMPLOYEES ;

SELECT DISTINCT FIRST_NAME, LAST_NAME
FROM  EMPLOYEES ;

select * from EMPLOYEES
where FIRST_NAME = 'Ellen';



SELECT FIRST_NAME,LAST_NAME
FROM EMPLOYEES
WHERE SALARY = 11000;


-- Display the Employee FIRST_NAME, LAST_NAME,SALARY
-- for the employee with SALARY 4800 and FIRST_NAME David
SELECT FIRST_NAME, LAST_NAME,SALARY
FROM EMPLOYEES
WHERE FIRST_NAME ='David' AND SALARY = 4800 ;


-- Display the Employee FIRST_NAME, LAST_NAME,SALARY
-- for the employee with SALARY 4800 OR FIRST_NAME David
-- LOCATOR OR
SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE FIRST_NAME= 'David' OR SALARY=4800 ;

-- Display the employees that make more than 5000 and less than 12000
/*
SELECT FIRST_NAME ,LAST_NAME,SALARY
FROM EMPLOYEES WHERE SALARY > 5000 AND SALARY < 12000;
*/
SELECT * FROM EMPLOYEES
WHERE SALARY > 5000 AND SALARY < 12000 ;

-- Display the employees that have JOB_ID of
-- AD_VP
-- AD_ASST
-- FI_ACCOUNT
-- AC_ACCOUNT
SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'AD_VP'
   OR  JOB_ID = 'AD_ASST'
   OR  JOB_ID = 'FI_ACCOUNT'
   OR  JOB_ID = 'AC_ACCOUNT' ;

-- USING KEYWORD IN for multiple possible value of same column in condition
SELECT FIRST_NAME,JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN ('AD_VP','AD_ASST','FI_ACCOUNT','AC_ACCOUNT') ;

-- for equality check !=  <>  ,
--- FIND OUT ALL REGIONS EXPECT THE REGION WITH REGION_ID OF 1
SELECT * FROM REGIONS
--WHERE REGION_ID <> 1;
WHERE REGION_ID ! =1 ;

--- FIND OUT ALL REGIONS EXPECT THE REGION WITH REGION_NAME OF Americas
SELECT * FROM REGIONS
WHERE REGIONS.REGION_NAME <> 'Americas' ;


-- Display the employees that DOES NOT make
-- more than 5000 and less than 12000
SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND  12000;




SELECT FIRST_NAME,JOB_ID
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('AD_VP','AD_ASST','FI_ACCOUNT','AC_ACCOUNT');


SELECT * FROM DEPARTMENTS
WHERE MANAGER_ID IS NULL ;

SELECT * FROM DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL ; -- 11 ROWS
-- SORTING THE RESULT IN ASCENDING (LOW TO HIGH )
--  OR DESCENDING ORDER(HIGH TO LOW )
-- ORDER BY Clause can be used to order the result of your query
-- It use either column name or column index
-- It must be the last part of the statement
-- ASC for (LOW TO HIGH ) by default ,
-- DESC  (HIGH TO LOW )


SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
ORDER BY FIRST_NAME ;

-- Display Employee FIRST_NAME and LAST_NAME and Salary
-- try to sort by below criteria separately
-- FIRST_NAME ASC
-- Salary DESC
-- LAST_NAME DESC
SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
--ORDER BY FIRST_NAME ASC ;
--ORDER BY LAST_NAME DESC ;
--ORDER BY SALARY DESC ;
ORDER BY 1 DESC ;
--ORDER BY LAST_NAME DESC ;
-- ORDER BY 1 DESC ; -- THIS MEANS SORT THE RESULT BY FIRST COLUMN
-- SQL INDEX START WITH 1 NOT 0 !!!!!!!!!!!!!



-- WHAT ABOUT THE PARTIAL SEARCH
-- WE USE LIKE AND % (WILD CARD)
--  % can represent 0 or more character of any kind
--  _ can represent exactly one character of any kind
-- DISPLAY ALL THE FIRST_NAME THAT START WITH LETTER A IN EMPLOYEES TABLES
SELECT FIRST_NAME
FROM EMPLOYEES
--WHERE FIRST_NAME LIKE 'A%';
-- DISPLAY ALL THE FIRST_NAME THAT END WITH LETTER a IN EMPLOYEES TABLES
WHERE FIRST_NAME LIKE '%a';

-- DISPLAY ALL THE FIRST_NAME THAT END WITH LETTER a IN EMPLOYEES TABLES
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%'  ;  -- 16 ROWS



