-- SUB QUERY : QUERY INSIDE ANOTHER QUERY


-- FIND OUT MAX SALARY FROM EMPLOYEES
SELECT MAX(SALARY)
FROM EMPLOYEES ;

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = 24000 ;

-- WE HARD CODED THE VALUE OF 24000 WE GOT FROM FIST QUERY INTO SECOND QUERY
-- NOW JUST LIKE FUNCTION CALL WE CAN USE THIS QUERY
-- AS A BLOCK OF QUERY THAT GENERATE MAX SALARY ANYTIME
-- SO EVEN IF MAX SALARY CHANGE AT SOME POINT WE WOULD GET CORRECT RESULT
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY = (    SELECT MAX(SALARY)
                    FROM EMPLOYEES
)
;
-- FIND OUT THE NAME OF THE EMPLOYEE THAT MAKE LEAST SALARY
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY =  ( SELECT MIN(SALARY) FROM EMPLOYEES ) ;

-- FIND OUT THE NAME , SALARY OF THE EMPLOYEES THAT MAKE MORE THAN AVERAGE SALARY
SELECT AVG(SALARY) FROM EMPLOYEES ;

SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) ;


--- DISPLAY ALL EMPLOYEES IF SALARY IS NOT 24000
--- AND FIND MAX
-- ALSO KNOWN AS (AKA) SECOND MAX SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY != ( SELECT MAX(SALARY) FROM EMPLOYEES );





-- WHAT ABOUT 3RD
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < 17000 ;-- FILTER ALL SALARY LESS THAN 2ND MAX
--- JUST REPLACE THE 17000 with above query
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < ( SELECT MAX(SALARY)
                 FROM EMPLOYEES
                 WHERE SALARY != ( SELECT MAX(SALARY) FROM EMPLOYEES ) );






-- find out the Department_id of Executive
SELECT DEPARTMENT_ID FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Executive' ;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90 ;
-- NOW COMBINE THEM
SELECT FIRST_NAME FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS
                       WHERE DEPARTMENT_NAME = 'Executive') ;

